const message = {
  Failed: 0,
  OK: 1,
  SUCCESS: "Success",
  FAIL: "Failed",
  F_NAME_REQ: "Full name is required.",
  ALREADY_REG: "Already register.",
  REQUIRED_FIELD_MISSING: "Required field is missing.",
  PASSWORD_NOT_MATCH: "Please Enter correct password.",
  CHECK_EMAIL_PASS: "Please check email & password.",
  SOMETHING_WENT_WRONG: "Something went wrong.",
  INVALID_ID_PWD: "Email and password does not match.",
  NO_ACCOUNT_FOUND: "Account not found.",
  ACCOUNT_SUCC_PASSWORD_MATCH:
    "You already registred with our platform,please use existing password.",
  EMAIL_ALREADY_EXISTS: "E-mail address already exists.",
  EMAIL_NOT_EXISTS: "Please enter correct email.",
  NAME_REQ: "Name is required",
  PRICE_REQ: "Price is required",
  CAT_REQ: "Category id is required",
  EMAIL_REQ: "Email is required",
  PASS_REQ: "Password is required",
  PASS_NOT_MATCH_: "Password not match please check it.",
  CON_PASS: "Conformpassword is required",
  FORGOT_PAAS: "Forgot Password",
  PSWD_UPDATED_SUCC: "Password updated successfully.",
  TRY_AGAIN: "Please try again.",
  USER_UPDATED_SUCC: "User details updated successfully.",
  NO_PAGE_FOUND: "Page not found",
  NO_DATA: "No data found",
  Id_REQ: "ID is required",
};

module.exports.message = message;
